default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  port: 5432
  timeout: 5000


development:
  <<: *default
  database: anything_backend_development_new3
  username: postgres
  password: postgres
  host: localhost
  pool: 15


# development:
#   <<: *default
#   host: detail-fetch-backend.postgres.database.azure.com
#   database: detail-fetch-db
#   username: postgres@detail-fetch-backend
#   password: Protonshub@321


# test:
#   <<: *default
#   database: cheers_on_demand_backend_test

# staging:
#   <<: *default
#   database: anything_backend_development

#   database: <%= ENV.fetch("DB_NAME") { 'cheers_on_demand_backend_staging' } %>

# production:
#   <<: *default
#   database: <%= ENV.fetch("DB_NAME") { 'cheers_on_demand_backend_production' } %>


# production:
#   <<: *default
#   host: detail-fetch-backend.postgres.database.azure.com
#   database: detail-fetch-db
#   username: postgres@detail-fetch-backend
#   password: Protonshub@321



# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
